# Reference: https://github.com/i3/i3/blob/next/etc/config

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

[mode.main.binding]
# alt-enter = 'exec-and-forget open -n /System/Applications/Utilities/Terminal.app'
alt-enter = 'exec-and-forget open -n /Applications/Ghostty.app'
# open a floating terminal window
alt-shift-enter = '''exec-and-forget sh -c '
# remember what’s already on screen
baseline=$(aerospace list-windows --workspace visible \
          --app-bundle-id com.mitchellh.ghostty --format "%{window-id}")

open -na /Applications/Ghostty.app        # launch new window

# wait ≤200ms for a window ID we haven’t seen yet
for _ in {1..20}; do
  id=$(aerospace list-windows --workspace visible \
        --app-bundle-id com.mitchellh.ghostty --format "%{window-id}" \
        | grep -Fvx "$baseline" | tail -1)
  [ -n "$id" ] && break
  sleep 0.01
done

[ -n "$id" ] && aerospace layout floating --window-id "$id"
' '''
#alt-enter = '''exec-and-forget osascript -e '
#tell application "/Applications/Ghostty.app"
#    do script
#    activate
#end tell'
#'''

alt-o = 'exec-and-forget pmset displaysleepnow'

alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# we move to join-with for more reliable, albeit less i3 like window stacking
# alt-b = 'split horizontal'
# alt-v = 'split vertical'
alt-b = 'join-with left'
alt-v = 'join-with up'

alt-f = 'fullscreen'
alt-shift-f = 'macos-native-fullscreen'

alt-s = 'layout v_accordion' # 'layout stacking' in i3
alt-w = 'layout h_accordion' # 'layout tabbed' in i3
alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

ctrl-left = "workspace prev"
ctrl-right = "workspace next"

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

# better solution might be move-node-to-monitor with --focus-follows-window
alt-shift-left = "move-workspace-to-monitor next"
alt-shift-right = "move-workspace-to-monitor prev"
alt-shift-c = 'reload-config'
alt-r = 'mode resize'

# [workspace-to-monitor-force-assignment]
# 1 = 'main'
# 2 = 'main'
# 3 = 'main'
# 4 = 'main'
# 5 = 'main'
# 6 = ['secondary', 'main']
# 7 = ['secondary', 'main']
# 8 = ['secondary', 'main']
# 9 = ['secondary', 'main']
# 0 = ['secondary', 'main']

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'
